---

- name: Getting PhantomJS
  unarchive:
    copy: no
    src: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /tmp
    list_files: yes
  register: phantomjs

- name: Copying PhantomJS executable to /usr/local/bin
  copy:
    src: /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    remote_src: yes
    dest: /usr/local/bin
    mode: 0555
  when: phantomjs.changed
