#---------------------------------------- APT ------------------------------------------
apt_install_openvpn: true

#------------------------------------- APPACHE 2 ---------------------------------------
apache_logroot: /var/log/apache2
apache2_mods_enabled:
  - rewrite
  - ssl
  - headers
  - http2

#------------------------------------- VHOSTS ------------------------------------------
vhosts:
# ...
# there are was a lot of hosts with settings
# ...

#  Vhosts example
#
#  vhosts:
#    project.loc:
#      docroot: "/work/webroot/project/backend/desktop/web"  # Required
#      aliases: "www.project.loc"                                            # Optional
#      docroot_options:                                                      # Optional
#        - Options Indexes FollowSymLinks MultiViews
#        - AllowOverride All
#      php_options:                                                          # Optional
#        - php_value max_input_time -1
#        - php_value max_execution_time 0

#----------------------------------- PHP SETTINGS  -------------------------------------
# If you adding section for php_options, you need to modify role!
php_options:
  PHP:
    max_execution_time: 500
    memory_limit: 1024M
    error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
    display_errors: Off
    display_startup_errors: Off
    track_errors: Off
    log_errors: On
    ignore_repeated_errors: Off
    post_max_size: 1024M
    upload_max_filesize: 1024M
    session.gc_divisor: 20000
    session.gc_maxlifetime: 3600
    max_input_vars: 100000
  Date:
    date.timezone: "Europe/Kiev"

php_options_cli:
  PHP:
    max_execution_time: 0
    memory_limit: 16G

#------------------------------------ Apache SETTINGS ---------------------------------------
apache:
  buffered_logs: "ON"

#------------------------------------ DB SETTINGS ---------------------------------------
mysql:
  datadir: /mnt/db/mysql
  logroot: /var/log/mysql
  tmp_table_size: 128M

# query_cache_typedeprecated
  query_cache_type: 0

  max_heap_table_size: 128M
  key_buffer_size: 128M
  max_allowed_packet: 16M
  thread_stack: 4M
  thread_cache_size: 32

# query_cache_limit is deprecated
  query_cache_limit: 0

  max_binlog_size: 1073741824
  sql_mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
#sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
  innodb_buffer_pool_size: 96G
  innodb_log_file_size: 512M
  innodb_log_buffer_size: 64M

db_user: db_user_example
db_password: db_password_example
db_priv: "*.*:ALL"

#------------------------------------ SVN SETTINGS -------------------------------------
svn_username: svn_username_example
svn_password: svn_password_example

#------------------------------- DEPLOY AUTH SETTINGS ----------------------------------
deploy_username: deploy_username_example
deploy_password: deploy_password_example

#--------------------------------- GIT-KEYS USERS --------------------------------------
git_keys_users:
  - www-data

#------------------------------- PROJECT SETTINGS -----------------------------------
project_path: /work/webroot/project
project_env: Production
project_composer_options: '--no-dev'
project_submodules: no
project_disable_cron: yes


#------------------------------------ XDEBUG -------------------------------------------
#xdebug:
#  profiler_output_dir: '/tmp'\

#----------------------------------- OpCache -------------------------------------------
opcache:
  opcache.memory_consumption: 128
  opcache.interned_strings_buffer: 8
  opcache.max_accelerated_files: 4000
  opcache.revalidate_freq: 60
  opcache.fast_shutdown: 1
  opcache.enable_cli: 1

#----------------------------------- Zabbix -------------------------------------------
zabbix:
  server: 10.128.0.6,80.90.224.22,85.238.105.165
  server_active: 10.128.0.6,80.90.224.22,85.238.105.165
  server_ip: 10.128.0.6
  hostname: project.com
  include: /etc/zabbix/zabbix_agentd.conf.d/
  scripts_dir: /etc/zabbix/scripts
  timeout: 10
